import{S as q,a as y,i as w}from"./assets/vendor-5401a4b0.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();let f;function P({largeImageURL:e,webformatURL:a,tags:o,likes:c,views:t,comments:r,downloads:s}){return`<li class="gallery-item">
        <a class="gallery-link" href="${e}">
            <img class="gallery-image" src="${a}" alt="${o}" />
        </a>
        <div class="info-box">
            <p>Likes:<span> ${c}</span></p>
            <p>Views:<span> ${t}</span></p>
            <p>Comments:<span> ${r}</span></p>
            <p>Downloads:<span> ${s}</span> </p>
        </div>
    </li>`}function h(e){const a=e.map(P).join("");n.gallery.insertAdjacentHTML("beforeend",a),f?x():v()}function v(){f=new q(".gallery a",{captionDelay:250,captionsData:"alt",captionPosition:"bottom"})}function x(){f.refresh()}const b=15;async function L(){return y.defaults.baseURL="https://pixabay.com/api/",(await y.get("",{params:{key:"42262858-7b31826aafbc45fb5436f2ee9",image_type:"photo",orientation:"horizontal",safesearch:"true",q:u,page:i,per_page:b}})).data}let u="",i=1;const n={formEl:document.querySelector(".form"),inputEl:document.querySelector(".query"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoad:document.querySelector(".load-more-btn")},m=n.gallery.querySelector(".gallery-item");n.formEl.addEventListener("submit",E);n.btnLoad.addEventListener("click",F);async function E(e){if(e.preventDefault(),i=1,d(),u=e.target.elements.query.value.trim(),!u){l("Please fill in the input field");return}try{g();const o=await L(i,u);o.hits.length>0?(h(o.hits),M(),O()):(g(),p(),l("Sorry, there are no images matching your search query. Please try again!")),S(o.totalHits,i)}catch(o){console.error("Error data:",o),o.message.includes("network")?l("Please check your internet connection"):l("An error occurred. Please try again later.")}finally{d(),e.target.reset()}}async function F(){d(),i+=1;const e=await L();h(e.hits),S(e.totalHits,i),d()}function d(){n.loader.classList.toggle("hidden")}function l(e){w.show({message:e,messageColor:"#FFFFFF",backgroundColor:"#B51B1B",position:"topRight"})}function M(){n.btnLoad.style.display="block"}function p(){n.btnLoad.style.display="none"}function O(){if(m){const e=m.getClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}function g(){n.gallery.innerHTML="",p()}function S(e,a){Math.ceil(e/b)===a&&(p(),l("We're sorry, but you've reached the end of search results."))}
//# sourceMappingURL=commonHelpers.js.map
